### ISSUE TITLE
Multiple Instances

### ISSUE THREAD

**Issue by bthurow** [simonsteele/pn#116]
I'm really starting to like this editor over Notepad++, but there's one feature N++ has that I love but is missing in Programmer's Notepad- the ability to have multiple instances running.  A lot of time I need to look at files side-by-side and I can't do that with pn.
Any chance of giving an option to open a file in a new window like N++ does?

**Comment by Unh0lyTigg** [comment]
Under General Options (via Tools > Options), under the Settings heading, the first checkbox should be "Allow multiple instances of Programmer's Notepad to start". Checking this should do what you want. You can also click the un-maximize the current file tab, which will allow you to have files side-by-side within the same parent editor window.
