### ISSUE TITLE
Unlike notepad.exe, PN.exe doesn't prevent OS sign out (or power off or restart) with unsaved changes.  (at least on Win10-64bit-pro)

### ISSUE THREAD

**Issue by tmek** [simonsteele/pn#125]
(note: my OS is Windows 10 64-bit Pro)

If there are unsaved changes in notepad.exe and the user chooses to sign out of Windows (or power off or restart), Windows will notify the user notepad.exe is preventing the system from shutting down and give them the option to force shutdown or cancel and save their changes.

When there are unsaved changes in pn.exe it simply just allows the system to shutdown.  This seems very undesirable to me and would result in unexpected loss of information.

**Comment by simonsteele** [comment]
Please check with the new 2.4.2 version, there was a fix for that included.
