### ISSUE TITLE
Download links are broken

### ISSUE THREAD

**Issue by urbanhusky** [simonsteele/pn#130]
The download links on http://www.pnotepad.org/download/ lead to 404s

**Comment by Xorcist77** [comment]
I'm seeing the same thing, links starting with:

http://www.pnotepad.org/bugs/
http://www.pnotepad.org/files
http://pnotepad.googlecode.com/files

and

http://www.pnotepad.org/docs/howto/translate_programmer_s_notepad

all lead to 404's.
