### ISSUE TITLE
Awk

### ISSUE THREAD

**Issue by ghost** [simonsteele/pn#152]
Please create syntax highlighting for Awk, thank you.

**Comment by svnpenn** [comment]
Here is workaround:

http://github.com/zufuliu/notepad2

**Comment by svnpenn** [comment]
https://github.com/mirror/scintilla/issues/1

**Comment by svnpenn** [comment]
https://github.com/XhmikosR/notepad2-mod/issues/208

**Comment by svnpenn** [comment]
https://github.com/mirror/scite/issues/1

**Comment by svnpenn** [comment]
https://github.com/Microsoft/vscode/issues/42265

**Comment by svnpenn** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1620
