### ISSUE TITLE
Won't let me save sometimes, only lets me do "Save As".

### ISSUE THREAD

**Issue by genechuah** [simonsteele/pn#187]
Happens randomly. Won't let me save sometimes, only lets me do "Save As". Says that the file can't be written or something like that. However there's no good reason for that. It's a file that only I am writing to, no other system process (it's not a logfile). I'm on Windows 10 Pro, Alienware R17.

**Comment by JoseQuintas** [comment]
May be file is readonly, or file is on na protected folder.
I have this issue when editing my.ini with mysql configuration.
to edit this file, I open editor as administrator.
