### ISSUE TITLE
Window title unhelpful

### ISSUE THREAD

**Issue by sammoth** [simonsteele/pn#19]
Most windows software structures its window titles as something like `Document Name - Software Name`, but PN uses `Programmer's Notepad - [Document Name]`, which is unhelpful when the Windows taskbar is set to "Never combine" mode so that window titles are shown in the taskbar - PN's title is always truncated to `Programmer's Notep...` so you can never identify a PN window by the current open document.

**Comment by simonsteele** [comment]
Same as #90
