### ISSUE TITLE
support persian and Arabic Languages

### ISSUE THREAD

**Issue by forghan89** [simonsteele/pn#192]
Hello

I have a problem with Programmer's Notepad.
"Programmer's Notepad" doesn't support persian and Arabic Languages. 
Please fix this issue in the next update.

Thanks
![persian](https://user-images.githubusercontent.com/47449690/65760293-9a4a9a80-e129-11e9-8268-4d061dd56b34.png)

**Comment by Thomassso** [comment]
Give it a second try: hit [ALT]+[ENTER] and then change the Encoding from Default to UTF-8. The default Encoding can be set in the Tools/Options menu and Defaults leaf in the Options tree.

Also check the Fonts settings in the Tools/Options menu. You need to configure a font which contains Arabic letters.
