### ISSUE TITLE
programmer's notepad

### ISSUE THREAD

**Issue by Bielzebub1981** [simonsteele/pn#208]
when trying to make document regarding Eurovision, trying to do it in such a way that the information for each country or act is like a 5 or 6 line story. Main problem bing that programmer notepad seems unable to recognise language text such as that used in Yugoslavian, seemingly referred to as Serbo-Croatian (https://en.wikipedia.org/wiki/Serbo-Croatian)

**Comment by veganaiZe** [comment]
Seems to work for me...
![image](https://user-images.githubusercontent.com/7102064/176791202-05ca6c73-eb68-4241-824a-0617d0d40e97.png)

Which font are you using (in `Tools`->`Options`->`Fonts and Colours`)?  I'm using Courier New.

Your font will need to include support for those characters.

**Comment by Bielzebub1981** [comment]
copied the below from [Eurovision 1962](https://en.wikipedia.org/wiki/Eurovision_Song_Contest_1962) 
Participants and results

However, as you can see, there are a lot of ? marks yet font is set to Courier New

Yugoslavia	Lola Novakovic	"Ne pali svetla u sumrak" (?? ???? ?????? ? ??????)	Serbo-Croatian	4	10

**Comment by veganaiZe** [comment]
`Tools` -> `Options` -> `General` -> `Defaults`...
![image](https://user-images.githubusercontent.com/7102064/177159604-19902979-9f38-4854-9f70-7b82c7ccf1fb.png)

* Which version of Windows are you running it on?  
* Which language/locale is Windows set to?  
* Which fonts have you tried?  
* Can you get the text to work in any other editors?

https://www.fontsquirrel.com/fonts/list/find_fonts?filter%5Blanguages%5D%5B0%5D=croatian&filter%5Blanguages%5D%5B1%5D=serbian  

_It's still working for me (with Courier New)..._
![image](https://user-images.githubusercontent.com/7102064/177158650-10b62d67-16d6-4c3c-87d8-3a977508df39.png)

**Comment by Bielzebub1981** [comment]
![image](https://user-images.githubusercontent.com/4096685/177426049-9eb51f78-5ade-4b15-b581-521a7ef54937.png)

as you can see here, the standard WINDOWS TEXT application posted the Не пали светла у сумрак
so why can't Programmer's notepad ?

Current Font: Courier New

---
Edition: Windows 10 Enterprise
Version: 21H2
Installed on: 14/‎03/‎2022
OS build:	19044.1806
Experience: Windows Feature Experience Pack 120.2212.4180.0
---

**Comment by veganaiZe** [comment]
![image](https://user-images.githubusercontent.com/7102064/177439139-909de32e-166f-464d-be76-4dec6102e7d8.png)

**Comment by Bielzebub1981** [comment]
UTF-No Mark seems to have sorted the issue 😄 
---

On looking at the encoding options under file, 
ANSI
UTF-8
UTF-16 Big Endian
UTF-16 Little Endian
UTF-No Mark

then, if you go along to Tools > Options> General  and click on Default and down to Encoding
ANSI
UTF-8
UTF-8 No BOM
UTF-16 Big Endian
UTF-16 Little Endian

how come one has No Mark, but other has No BOM ?

**Comment by veganaiZe** [comment]
BOM means "byte order mark".  It's intention's to signify the order in which to expect the bytes of each character.  But it tends to cause more trouble than it's worth with UTF-8...  So it's generally recommended to avoid it.

https://www.unicode.org/faq/utf_bom.html

_I'm glad your issue has been corrected!_
