### ISSUE TITLE
Fonts and colours ( Advanced )

### ISSUE THREAD

**Issue by Bielzebub1981** [simonsteele/pn#209]
You have options to customise from Scheme: Ada down to Scheme: XML

1) Why is there no option to customise Plain Text ?
2) Why is there no option to choose between Line End Markers active or not for every page you open ?
3) Why is there no option to choose between Line Number active or not for every page you open ?

**Comment by veganaiZe** [comment]
1. You can customize Plain Text by navigating to `Tools` -> `Options` -> `Fonts and Colours`...  Which will allow you to set the Base Style (ie. for plain text).
2. You can set Line End Markers, per file, at `View` -> `Line End Markers`.  To set them globally go to `Tools` -> `Options` -> `Defaults` and check `Visible Line Endings`.
3. You can set Line Numbers, per file, at `View` -> `Line Numbers`.  To set them globally go to `Tools` -> `Options` -> `Defaults` and check `Show Line Numbers`.

_Also note that you can open multiple (different) instances of Programmer's Notepad with the command-line option `--allowmulti`, if need be._

**Comment by Bielzebub1981** [comment]
d'oh

<img src="https://www.kindpng.com/picc/m/122-1222459_facepalm-emoji-png-man-face-palm-emoji-transparent.png" alt="Facepalm Emoji Png - Man Face Palm Emoji, Transparent Png@kindpng.com">

thankyou

**Comment by veganaiZe** [comment]
_No problem!_ :+1:
