### ISSUE TITLE
"Debug assertion failed" after building pn according to the instructions

### ISSUE THREAD

**Issue by dennisschagt** [simonsteele/pn#27]
After following the instructions at [pnotepad.org/docs/dev/how_to_compile_pn](http://www.pnotepad.org/docs/dev/how_to_compile_pn/) I started `pn.exe`. The window itself looks fine but it shows `Debug Assertion Failed`, Included here are a [dump](http://dschagt.nl/tmp/PN2_2.4.0.0.dmp) and a screenshot:
![image](https://cloud.githubusercontent.com/assets/4629607/6093002/80037246-aef7-11e4-8355-3c279197037d.png)

**Comment by simonsteele** [comment]
Sorry I didn't look at this until now. At a guess you were missing the Scintilla dll build (SciLexer.dll).
